name: auto-build
on:
  push:
    branches:
      - main
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: touch test2.txt